services:


  frontend:

    build:
      context: ./frontend

    container_name: react-app


    ports:
      - "3000:3000"


    depends_on:
      - json-server


    restart: always



  json-server:


    build:
      context: ./frontend/server


    container_name: json-server


    ports:
      - "3001:3001"


    volumes:
      - ./frontend/server/db.json:/app/db.json


    restart: always




  nginx:


    build:
      context: ./nginx


    container_name: nginx


    ports:
      - "80:80"


    depends_on:
      - frontend


    restart: always